import type { ProjectData, Metadata } from './extractor.js';

export type Lang = 'zh' | 'en';

/**
 * Extract the last 2 segments of a path for concise display.
 * e.g. "~/Developer/myorg/myrepo" -> "myorg/myrepo"
 */
function shortName(projectPath: string): string {
  const segments = projectPath.replace(/\/+$/, '').split('/').filter(Boolean);
  return segments.slice(-2).join('/');
}

/** 4.1 Generate the deterministic header: tweetable line + stats table */
export function generateHeader(metadata: Metadata, date: string): string {
  const [, month, day] = date.split('-');
  const datePart = `${Number(month)}/${Number(day)}`;
  const focusShort = shortName(metadata.focus.project);

  const tweetable = `${datePart}: ${metadata.totalProjects} projects \u00b7 ${metadata.totalSessions} sessions \u00b7 Focus: ${focusShort}`;

  const focusDisplay = `${shortName(metadata.focus.project)} (${metadata.focus.percentage}%)`;

  const table = [
    '| Metric | Value |',
    '|------|-----|',
    `| Projects | ${metadata.totalProjects} |`,
    `| Sessions | ${metadata.totalSessions} |`,
    `| Messages | ${metadata.totalUserMessages} |`,
    `| Active hours | ${metadata.activeHours} |`,
    `| Focus | ${focusDisplay} |`,
  ].join('\n');

  return tweetable + '\n\n' + table;
}

// --- Prompt system ---

const LANG_CONFIG: Record<Lang, { label: string; researchTag: string }> = {
  zh: { label: 'Chinese (中文)', researchTag: '调研' },
  en: { label: 'English', researchTag: 'Researched' },
};

function buildSystemPrompt(lang: Lang): string {
  const { label, researchTag } = LANG_CONFIG[lang];

  // Good/bad examples per language
  const goodExample = lang === 'zh'
    ? `## ~/Developer/myproject
- 实现了 extractor.ts 的 session JSONL 解析，支持 user (string) 和 assistant (array) 两种 content 格式
- 修复了 worktree 路径归并逻辑，正确处理 .claude/worktrees/ 下的 session
- 调研了 marked-terminal 方案，发现不满足需求，改为自写 renderer`
    : `## ~/Developer/myproject
- Implemented session JSONL parsing in extractor.ts, handling user (string) and assistant (array) content formats
- Fixed worktree path merging to correctly handle .claude/worktrees/ sessions
- Researched marked-terminal approach, found it insufficient, switched to custom renderer`;

  const badExample = lang === 'zh'
    ? `- 用户问了 XX，助手回答了 YY（复述对话过程）
- 完成。现在 research/ 下只有两个目录...（照搬原文）
- 推进了项目开发（太笼统，没有具体信息）
- 成功实现了一个优雅的解决方案来处理数据提取问题（修饰语过多）`
    : `- The user asked XX and the assistant replied YY (retelling conversation)
- Done. Now the research/ directory has two subdirectories... (copying raw text)
- Progressed on project development (too vague, no specifics)
- Successfully implemented an elegant solution for data extraction (too many filler words)`;

  return `<role>Daily report assistant. Distill Claude Code conversation logs into a structured work summary.</role>

<input_format>
Each project section starts with "## project-path".
Lines starting with "> " are user messages (what the developer asked or stated).
Infer what was accomplished from these messages. The actual work is implied by what was asked.
</input_format>

<output_rules>
Format: one "## project-path" heading per project, bullet points underneath.
Language: ${label}.
Granularity: 3-8 bullets per project. Each bullet ≤ 30 words.
Tag research: prefix with "${researchTag}" when the work was investigation, not implementation.
</output_rules>

<constraints>
NEVER copy raw text from the input. Paraphrase in your own words.
NEVER retell conversations ("user asked X, assistant said Y").
NEVER output stats tables, tweetable lines, or metadata (already generated by code).
NEVER add greetings, introductions, or closing summaries.
NEVER use filler words: "successfully", "elegantly", "efficiently", "properly".
NEVER use vague summaries: "progressed on", "worked on", "continued with".
Be specific: name files, functions, config keys, error types, tool names.
</constraints>

<good_example>
${goodExample}
</good_example>

<bad_example>
${badExample}
</bad_example>`;
}

// Build prompts once per language
const SYSTEM_PROMPTS: Record<Lang, string> = {
  zh: buildSystemPrompt('zh'),
  en: buildSystemPrompt('en'),
};

/** 4.2 Format the full prompt for a single claude -p call (all projects) */
export function formatPrompt(projects: ProjectData[], metadata: Metadata, lang: Lang = 'en'): string {
  const context = `<context>Today: ${metadata.totalProjects} projects, ${metadata.totalSessions} sessions, ${metadata.totalUserMessages} user messages.</context>`;
  const projectSections = projects.map(formatProjectSection);

  return [context, '', SYSTEM_PROMPTS[lang], '', '---', '', ...projectSections].join('\n');
}

/** 4.3 Format a per-project prompt (for split mode) */
export function formatProjectPrompt(project: ProjectData, lang: Lang = 'en'): string {
  return [SYSTEM_PROMPTS[lang], '', '---', '', formatProjectSection(project)].join('\n');
}

/** 4.4 Merge header + sorted project results */
export function mergeResults(header: string, projectResults: string[]): string {
  const sorted = [...projectResults].sort((a, b) => {
    const headingA = extractHeading(a);
    const headingB = extractHeading(b);
    return headingA.localeCompare(headingB);
  });

  return header + '\n\n' + sorted.join('\n\n');
}

// --- Internal helpers ---

const MAX_MSG_CHARS = 500;

function truncateText(text: string): string {
  if (text.length <= MAX_MSG_CHARS) return text;
  return text.slice(0, MAX_MSG_CHARS) + '... (truncated)';
}

function formatProjectSection(project: ProjectData): string {
  const lines: string[] = [`## ${project.path}`];

  for (const session of project.sessions) {
    for (const msg of session.messages) {
      if (msg.role === 'user') {
        lines.push(`> ${truncateText(msg.text)}`);
      }
    }
  }

  for (const wt of project.worktrees) {
    lines.push('', `### Worktree: ${wt.name}`);
    for (const session of wt.sessions) {
      for (const msg of session.messages) {
        if (msg.role === 'user') {
          lines.push(`> ${truncateText(msg.text)}`);
        }
      }
    }
  }

  return lines.join('\n');
}

function extractHeading(text: string): string {
  const match = text.match(/^## (.+)/m);
  return match ? match[1] : '';
}
