import type { ProjectData, Metadata } from './extractor.js';

export type Lang = 'zh' | 'en';

/**
 * Extract the last 2 segments of a path for concise display.
 * e.g. "~/Developer/myorg/myrepo" -> "myorg/myrepo"
 */
function shortName(projectPath: string): string {
  const segments = projectPath.replace(/\/+$/, '').split('/').filter(Boolean);
  return segments.slice(-2).join('/');
}

/** 4.1 Generate the deterministic header: tweetable line + stats table */
export function generateHeader(metadata: Metadata, date: string): string {
  const [, month, day] = date.split('-');
  const datePart = `${Number(month)}/${Number(day)}`;
  const focusShort = shortName(metadata.focus.project);

  const tweetable = `${datePart}: ${metadata.totalProjects} projects \u00b7 ${metadata.totalSessions} sessions \u00b7 Focus: ${focusShort}`;

  const focusDisplay = `${shortName(metadata.focus.project)} (${metadata.focus.percentage}%)`;

  const table = [
    '| Metric | Value |',
    '|------|-----|',
    `| Projects | ${metadata.totalProjects} |`,
    `| Sessions | ${metadata.totalSessions} |`,
    `| Messages | ${metadata.totalUserMessages} |`,
    `| Active hours | ${metadata.activeHours} |`,
    `| Focus | ${focusDisplay} |`,
  ].join('\n');

  return tweetable + '\n\n' + table;
}

// --- System instructions per language ---

const INSTRUCTIONS: Record<Lang, { system: string; context: (m: Metadata) => string; separator: string; projectSeparator: string }> = {
  zh: {
    system: `You are a senior engineer's daily report assistant. Distill the following Claude Code conversation logs into a structured daily work summary.

Rules:
- Use ## project-path as heading for each project
- List key work items as bullet points under each heading
- Extract only "what was done" and "what was decided" — do not retell conversations
- Paraphrase in your own words — never copy raw text
- Tag research work as "调研" (e.g. "调研了 XX 方案")
- Do NOT output stats tables or tweetable summaries (already generated by code)
- Do NOT output greetings or closing summaries
- Language: Chinese (中文)
- Style: concise, factual, like a standup report

Good output example:
## ~/Developer/myproject
- 实现了 extractor.ts 的 session JSONL 解析，支持 user (string) 和 assistant (array) 两种 content 格式
- 修复了 worktree 路径归并逻辑，正确处理 .claude/worktrees/ 下的 session
- 调研了 marked-terminal 的渲染方案，发现不满足需求，改为自写 renderer

Bad output (do NOT do this):
- The user asked XX and the assistant replied YY
- Done. Now the research/ directory has two subdirectories... (this is copying raw text)`,
    context: (m) => `Context: today has ${m.totalProjects} projects, ${m.totalSessions} sessions, ${m.totalUserMessages} messages`,
    separator: 'Below are today\'s conversation logs:',
    projectSeparator: 'Below are this project\'s conversation logs:',
  },
  en: {
    system: `You are a senior engineer's daily report assistant. Distill the following Claude Code conversation logs into a structured daily work summary.

Rules:
- Use ## project-path as heading for each project
- List key work items as bullet points under each heading
- Extract only "what was done" and "what was decided" — do not retell conversations
- Paraphrase in your own words — never copy raw text
- Tag research work explicitly (e.g. "Researched XX approach")
- Do NOT output stats tables or tweetable summaries (already generated by code)
- Do NOT output greetings or closing summaries
- Language: English
- Style: concise, factual, like a standup report

Good output example:
## ~/Developer/myproject
- Implemented session JSONL parsing in extractor.ts, handling both user (string) and assistant (array) content formats
- Fixed worktree path merging logic to correctly handle .claude/worktrees/ sessions
- Researched marked-terminal rendering approach, found it insufficient, switched to custom renderer

Bad output (do NOT do this):
- The user asked XX and the assistant replied YY
- Done. Now the research/ directory has two subdirectories... (this is copying raw text)`,
    context: (m) => `Context: today has ${m.totalProjects} projects, ${m.totalSessions} sessions, ${m.totalUserMessages} messages`,
    separator: 'Below are today\'s conversation logs:',
    projectSeparator: 'Below are this project\'s conversation logs:',
  },
};

/** 4.2 Format the full prompt for a single claude -p call (all projects) */
export function formatPrompt(projects: ProjectData[], metadata: Metadata, lang: Lang = 'zh'): string {
  const i = INSTRUCTIONS[lang];
  const context = i.context(metadata);
  const projectSections = projects.map(formatProjectSection);

  return [context, '', i.system, '', '---', '', i.separator, '', ...projectSections].join('\n');
}

/** 4.3 Format a per-project prompt (for split mode) */
export function formatProjectPrompt(project: ProjectData, lang: Lang = 'zh'): string {
  const i = INSTRUCTIONS[lang];
  return [i.system, '', '---', '', i.projectSeparator, '', formatProjectSection(project)].join('\n');
}

/** 4.4 Merge header + sorted project results */
export function mergeResults(header: string, projectResults: string[]): string {
  const sorted = [...projectResults].sort((a, b) => {
    const headingA = extractHeading(a);
    const headingB = extractHeading(b);
    return headingA.localeCompare(headingB);
  });

  return header + '\n\n' + sorted.join('\n\n');
}

// --- Internal helpers ---

const MAX_MSG_CHARS = 500;

function truncateText(text: string): string {
  if (text.length <= MAX_MSG_CHARS) return text;
  return text.slice(0, MAX_MSG_CHARS) + '... (truncated)';
}

function formatProjectSection(project: ProjectData): string {
  const lines: string[] = [`## ${project.path}`];

  for (const session of project.sessions) {
    for (const msg of session.messages) {
      if (msg.role === 'user') {
        lines.push(`> ${truncateText(msg.text)}`);
      }
    }
  }

  for (const wt of project.worktrees) {
    lines.push('', `### Worktree: ${wt.name}`);
    for (const session of wt.sessions) {
      for (const msg of session.messages) {
        if (msg.role === 'user') {
          lines.push(`> ${truncateText(msg.text)}`);
        }
      }
    }
  }

  return lines.join('\n');
}

function extractHeading(text: string): string {
  const match = text.match(/^## (.+)/m);
  return match ? match[1] : '';
}
